apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-admin-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-admin-db
        environment: dev
    spec:
      containers:
      - name: cbs-admin-db
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-admin-db
spec:
  ports:
  - port: 27017
  selector:
    app: cbs-admin-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-admin-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-admin-backend
        environment: dev
    spec:
      containers:
      - name: cbs-admin-backend
        image: karolikl/cbs-admin-backend:$BUILD_ID
        ports:
        - containerPort: 80
        env:
        - name: "KAFKA_BOUNDED_CONTEXT_SEND_TOPICS"
          value: "volunteerreporting;alert;usermanagement"
        - name: "KAFKA_BOUNDED_CONTEXT_TOPIC"
          value: "admin"
            
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-admin-backend
spec:
  ports:
  - port: 80
  selector:
    app: cbs-admin-backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-admin-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-admin-frontend
        environment: dev
    spec:
      containers:
      - name: cbs-admin-frontend
        image: karolikl/cbs-admin-frontend:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-admin-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cbs-admin-frontend