---
apiVersion: v1
kind: Service
metadata:
  name: admin-core
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: api
  selector:
    k9s-app: cbs-admin-core
---
apiVersion: v1
kind: Service
metadata:
  name: admin-web
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: ui
  selector:
    k9s-app: cbs-admin-web

---
apiVersion: v1
kind: Service
metadata:
  name: reporting-core
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: api
  selector:
    k9s-app: cbs-reporting-core
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-web
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: ui
  selector:
    k9s-app: cbs-reporting-web

---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-core
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: api
  selector:
    k9s-app: cbs-usermanagement-core
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-web
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: ui
  selector:
    k9s-app: cbs-usermanagement-web

---
apiVersion: v1
kind: Service
metadata:
  name: notification-core
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: api
  selector:
    k9s-app: cbs-notification-core
---
apiVersion: v1
kind: Service
metadata:
  name: notification-web
  namespace: cbs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    name: ui
  selector:
    k9s-app: cbs-notification-web
