apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-usermgmt-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-usermgmt-db
        environment: dev
    spec:
      containers:
      - name: cbs-usermgmt-db
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-usermgmt-db
spec:
  ports:
  - port: 27017
  selector:
    app: cbs-usermgmt-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-usermgmt-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-usermgmt-backend
        environment: dev
    spec:
      containers:
      - name: cbs-usermgmt-backend
        image: karolikl/cbs-usermgmt-backend:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-usermgmt-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cbs-usermgmt-backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-usermgmt-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-usermgmt-frontend
        environment: dev
    spec:
      containers:
      - name: cbs-usermgmt-frontend
        image: karolikl/cbs-usermgmt-frontend:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-usermgmt-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cbs-usermgmt-frontend