apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-volunteerreporting-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-volunteerreporting-db
        environment: dev
    spec:
      containers:
      - name: cbs-volunteerreporting-db
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: cbs-volunteerreporting-db
spec:
  ports:
  - port: 27017
  selector:
    app: cbs-volunteerreporting-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-volunteerreporting-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-volunteerreporting-backend
        environment: dev
    spec:
      containers:
      - name: cbs-volunteerreporting-backend
        image: karolikl/cbs-vr-backend:{{ .Values.services.volunteerreporting.backend.version }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.volunteerreporting.backend.service }}
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: cbs-volunteerreporting-backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cbs-volunteerreporting-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cbs-volunteerreporting-frontend
        environment: dev
    spec:
      containers:
      - name: cbs-volunteerreporting-frontend
        image: karolikl/cbs-vr-frontend:{{ .Values.services.volunteerreporting.frontend.version }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.volunteerreporting.frontend.service }}
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: cbs-volunteerreporting-frontend