version: 1.1.0-{build}

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

install:
  - ps: Install-Product node 8.6.0 x64

environment:
  TestsFolder: ../Source/Admin/Tests
  SlnFile: ../Source/Admin/Admin.sln
  WebBinFolder: ../Source/Admin/Web/bin
  AngularFolder: ../Source/Admin/Web.Angular

 only_commits:
   files:
     - Source/Admin/

build_script:
- ps: ./Build/build.ps1

test: off