apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
data:
  azurestorageaccountname: Y2JzMmRldg==
  azurestorageaccountkey: Q2hScGxZL3dhMjBzZmYrMTd1Qzl2aCtzQ3cySy9XZllIM0JXNklQbEdqTldwMkEzOXViN0RPOTd1T2tPWVVWNUZQMk8xRjNKc2NVa3pLSFRWZ2xWV0E9PQ==