version: '3'
networks:
  cbs-network:
services:
  cbs-reporting-core:
    image: redcrossredcrescent/cbs-vr-backend:latest
    build:
      context: "../../"
      dockerfile: "Source/VolunteerReporting/Core/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SWAGGER_PREFIX=swagger/reporting/
      - SWAGGER_BASE_PATH=volunteerreportingbackend/
    volumes:
      - "./cbs-tenants.json:/CBS/Core/.dolittle/tenants.json"
      - "./cbs-tenant-map.json:/CBS/Core/.dolittle/tenant-map.json"
      - "./cbs-reporting-resources.json:/CBS/Core/.dolittle/resources.json"
    networks:
      - "cbs-network"

  cbs-reporting-web:
    image: redcrossredcrescent/cbs-vr-frontend:latest
    build:
      context: "../../Source/"
      dockerfile: "VolunteerReporting/Web/Dockerfile"
      args:
        mode: "build-test"
    expose:
      - "80"
    networks:
      - "cbs-network"