version: '3'
networks:
  cbs-network:
services:
  cbs-notificationgateway-core:
    image: redcrossredcrescent/cbs-notification-backend:latest
    build:
      context: "../../"
      dockerfile: "Source/NotificationGateway/Core/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - "./cbs-notificationgateway-resources.json:/CBS/Core/.dolittle/resources.json"
      - "./cbs-notificationgateway-event-horizons.json:/CBS/Core/.dolittle/event-horizons.json"
    networks:
      - "cbs-network"

  cbs-notificationgateway-web:
    image: redcrossredcrescent/cbs-notification-frontend:latest
    build:
      context: "../../Source/"
      dockerfile: "NotificationGateway/Web/Dockerfile"
    expose:
      - "80"
    networks:
      - "cbs-network"