version: '3'
networks:
  cbs-network:
volumes: 
  cbs-cookie-volume:
services:
  # Bounded Contexts
  cbs-admin:
    image: redcrossredcrescent/cbs-admin:latest
    build:
      context: "../../"
      dockerfile: "Source/Admin/Dockerfile"
    volumes:
      - "./config/tenants.json:/CBS/Core/.dolittle/tenants.json"
      - "./config/tenant-map.json:/CBS/Core/.dolittle/tenant-map.json"
      - "./config/admin-resources.json:/CBS/Core/.dolittle/resources.json"
      - "./config/admin-event-horizons.json:/CBS/Core/.dolittle/event-horizons.json"
      - "cbs-cookie-volume:/CBS/Core/.cookies/"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OPENID_AUTHORITY
      - OPENID_CLIENT
    logging:
      driver: "none"
    networks:
      - "cbs-network"

  cbs-reporting:
    image: redcrossredcrescent/cbs-reporting:quickfix
    build:
      context: "../../"
      dockerfile: "Source/Reporting/Dockerfile"
    volumes:
      - "./config/tenants.json:/CBS/Core/.dolittle/tenants.json"
      - "./config/tenant-map.json:/CBS/Core/.dolittle/tenant-map.json"
      - "./config/reporting-resources.json:/CBS/Core/.dolittle/resources.json"
      - "./config/reporting-event-horizons.json:/CBS/Core/.dolittle/event-horizons.json"
      - "cbs-cookie-volume:/CBS/Core/.cookies/"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OPENID_AUTHORITY
      - OPENID_CLIENT
    #logging:
    #  driver: "none"
    networks:
      - "cbs-network"

  cbs-notificationgateway:
    image: redcrossredcrescent/cbs-notificationgateway:quickfix
    build:
      context: "../../"
      dockerfile: "Source/NotificationGateway/Dockerfile"
    volumes:
      - "./config/tenants.json:/CBS/Core/.dolittle/tenants.json"
      - "./config/tenant-map.json:/CBS/Core/.dolittle/tenant-map.json"
      - "./config/notificationgateway-resources.json:/CBS/Core/.dolittle/resources.json"
      - "./config/notificationgateway-event-horizons.json:/CBS/Core/.dolittle/event-horizons.json"
      - "./config/apikeyToTenant.json:/CBS/Core/apikeyToTenant.json"
      - "cbs-cookie-volume:/CBS/Core/.cookies/"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SMSEAGLE_APIKEY_TENANT_PATH=/CBS/Core/apikeyToTenant.json
      - OPENID_AUTHORITY
      - OPENID_CLIENT
    logging:
      driver: "none"
    networks:
      - "cbs-network"

  
  # Infrastructure
  cbs-ingress-nginx:
    image: "nginx:1.15-alpine"
    ports:
      - "8080:8080"
    logging:
      driver: "none"
    volumes:
      - "./config/nginx-default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - "cbs-network"

  cbs-mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    expose:
      - "27017"
    networks:
      - "cbs-network"
